import NavBar from "./Components/NavBar/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={`${inter.className} scroll-smooth bg-[#fff]`}>
      <body className='max-w-7xl mx-auto'>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
